/*
 * generated by Xtext
 */
package jolie.xtext;



/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class JolieRuntimeModule extends jolie.xtext.AbstractJolieRuntimeModule {

	

	
	
	
}
