/*
 * generated by Xtext
 */
package jolie.xtext.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class JolieUiModule extends jolie.xtext.ui.AbstractJolieUiModule {
	public JolieUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
