/*
* generated by Xtext
*/
package jolie.xtext.ui.outline;

import org.eclipse.xtext.ui.editor.outline.transformer.AbstractDeclarativeSemanticModelTransformer;

/**
 * customization of the default outline structure
 * 
 */
public class JolieTransformer extends AbstractDeclarativeSemanticModelTransformer {
	
}
