/*
 * generated by Xtext
 */
package org.eclipse.xtext;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class JolieRuntimeModule extends org.eclipse.xtext.AbstractJolieRuntimeModule {

}
