/*
* generated by Xtext
*/
package jolie.xtext.ui.contentassist.antlr;

import java.util.Collection;
import java.util.Map;
import java.util.HashMap;

import org.antlr.runtime.RecognitionException;
import org.eclipse.xtext.AbstractElement;
import org.eclipse.xtext.ui.editor.contentassist.antlr.AbstractContentAssistParser;
import org.eclipse.xtext.ui.editor.contentassist.antlr.FollowElement;
import org.eclipse.xtext.ui.editor.contentassist.antlr.internal.AbstractInternalContentAssistParser;

import com.google.inject.Inject;

import jolie.xtext.services.JolieGrammarAccess;

public class JolieParser extends AbstractContentAssistParser {
	
	@Inject
	private JolieGrammarAccess grammarAccess;
	
	private Map<AbstractElement, String> nameMappings;
	
	@Override
	protected jolie.xtext.ui.contentassist.antlr.internal.InternalJolieParser createParser() {
		jolie.xtext.ui.contentassist.antlr.internal.InternalJolieParser result = new jolie.xtext.ui.contentassist.antlr.internal.InternalJolieParser(null);
		result.setGrammarAccess(grammarAccess);
		return result;
	}
	
	@Override
	protected String getRuleName(AbstractElement element) {
		if (nameMappings == null) {
			nameMappings = new HashMap<AbstractElement, String>() {
				private static final long serialVersionUID = 1L;
				{
					put(grammarAccess.getProgramAccess().getAlternatives_0(), "rule__Program__Alternatives_0");
					put(grammarAccess.getSubtypesAccess().getAlternatives(), "rule__Subtypes__Alternatives");
					put(grammarAccess.getCardinalityAccess().getAlternatives(), "rule__Cardinality__Alternatives");
					put(grammarAccess.getCardinalityAccess().getAlternatives_2_3(), "rule__Cardinality__Alternatives_2_3");
					put(grammarAccess.getNative_typeAccess().getAlternatives(), "rule__Native_type__Alternatives");
					put(grammarAccess.getNative_type_subAccess().getAlternatives_1(), "rule__Native_type_sub__Alternatives_1");
					put(grammarAccess.getProcessAccess().getAlternatives(), "rule__Process__Alternatives");
					put(grammarAccess.getBasicStatementAccess().getAlternatives(), "rule__BasicStatement__Alternatives");
					put(grammarAccess.getRightSideAccess().getAlternatives(), "rule__RightSide__Alternatives");
					put(grammarAccess.getInstallFuncitonAccess().getAlternatives_0(), "rule__InstallFunciton__Alternatives_0");
					put(grammarAccess.getInstallFuncitonAccess().getAlternatives_3_1(), "rule__InstallFunciton__Alternatives_3_1");
					put(grammarAccess.getPreIncrementDecrementAccess().getAlternatives_0(), "rule__PreIncrementDecrement__Alternatives_0");
					put(grammarAccess.getConditionAccess().getAlternatives(), "rule__Condition__Alternatives");
					put(grammarAccess.getConditionAccess().getAlternatives_1_0(), "rule__Condition__Alternatives_1_0");
					put(grammarAccess.getRightConditionAccess().getAlternatives_0(), "rule__RightCondition__Alternatives_0");
					put(grammarAccess.getExpressionAccess().getOpAlternatives_1_1_0(), "rule__Expression__OpAlternatives_1_1_0");
					put(grammarAccess.getTerminalExpressionAccess().getAlternatives(), "rule__TerminalExpression__Alternatives");
					put(grammarAccess.getTerminalExpressionAccess().getAlternatives_4_0(), "rule__TerminalExpression__Alternatives_4_0");
					put(grammarAccess.getTerminalExpressionAccess().getAlternatives_5_1(), "rule__TerminalExpression__Alternatives_5_1");
					put(grammarAccess.getVariablePathAccess().getAlternatives(), "rule__VariablePath__Alternatives");
					put(grammarAccess.getVariablePathAccess().getAlternatives_0_4(), "rule__VariablePath__Alternatives_0_4");
					put(grammarAccess.getVariablePathAccess().getAlternatives_0_4_0_1(), "rule__VariablePath__Alternatives_0_4_0_1");
					put(grammarAccess.getVariablePathAccess().getAlternatives_1_2(), "rule__VariablePath__Alternatives_1_2");
					put(grammarAccess.getVariablePathAccess().getAlternatives_1_2_0_1(), "rule__VariablePath__Alternatives_1_2_0_1");
					put(grammarAccess.getNDChoiceStatementAccess().getAlternatives_1_1(), "rule__NDChoiceStatement__Alternatives_1_1");
					put(grammarAccess.getPortAccess().getAlternatives(), "rule__Port__Alternatives");
					put(grammarAccess.getTypeDefinitionAccess().getAlternatives(), "rule__TypeDefinition__Alternatives");
					put(grammarAccess.getUriAccess().getAlternatives(), "rule__Uri__Alternatives");
					put(grammarAccess.getProgramAccess().getGroup(), "rule__Program__Group__0");
					put(grammarAccess.getExecutionAccess().getGroup(), "rule__Execution__Group__0");
					put(grammarAccess.getIncludeAccess().getGroup(), "rule__Include__Group__0");
					put(grammarAccess.getTypeAccess().getGroup(), "rule__Type__Group__0");
					put(grammarAccess.getTypedefAccess().getGroup(), "rule__Typedef__Group__0");
					put(grammarAccess.getSubtypesAccess().getGroup_0(), "rule__Subtypes__Group_0__0");
					put(grammarAccess.getSubtypesAccess().getGroup_0_1(), "rule__Subtypes__Group_0_1__0");
					put(grammarAccess.getSubtypesAccess().getGroup_1(), "rule__Subtypes__Group_1__0");
					put(grammarAccess.getCardinalityAccess().getGroup_2(), "rule__Cardinality__Group_2__0");
					put(grammarAccess.getNative_type_subAccess().getGroup(), "rule__Native_type_sub__Group__0");
					put(grammarAccess.getDefineAccess().getGroup(), "rule__Define__Group__0");
					put(grammarAccess.getInitAccess().getGroup(), "rule__Init__Group__0");
					put(grammarAccess.getMainAccess().getGroup(), "rule__Main__Group__0");
					put(grammarAccess.getMainProcessAccess().getGroup(), "rule__MainProcess__Group__0");
					put(grammarAccess.getProcessAccess().getGroup_0(), "rule__Process__Group_0__0");
					put(grammarAccess.getProcessAccess().getGroup_1(), "rule__Process__Group_1__0");
					put(grammarAccess.getParallelStatementAccess().getGroup(), "rule__ParallelStatement__Group__0");
					put(grammarAccess.getParallelStatementAccess().getGroup_1(), "rule__ParallelStatement__Group_1__0");
					put(grammarAccess.getParallelStatementAccess().getGroup_1_1(), "rule__ParallelStatement__Group_1_1__0");
					put(grammarAccess.getSequenceStatementAccess().getGroup(), "rule__SequenceStatement__Group__0");
					put(grammarAccess.getSequenceStatementAccess().getGroup_1(), "rule__SequenceStatement__Group_1__0");
					put(grammarAccess.getSequenceStatementAccess().getGroup_1_1(), "rule__SequenceStatement__Group_1_1__0");
					put(grammarAccess.getBasicStatementAccess().getGroup_9(), "rule__BasicStatement__Group_9__0");
					put(grammarAccess.getLinkInAccess().getGroup(), "rule__LinkIn__Group__0");
					put(grammarAccess.getAssignStatementOrPostIncrementDecrementOrInputOperationAccess().getGroup(), "rule__AssignStatementOrPostIncrementDecrementOrInputOperation__Group__0");
					put(grammarAccess.getRightSideAccess().getGroup_0(), "rule__RightSide__Group_0__0");
					put(grammarAccess.getRightSideAccess().getGroup_1(), "rule__RightSide__Group_1__0");
					put(grammarAccess.getRightSideAccess().getGroup_2(), "rule__RightSide__Group_2__0");
					put(grammarAccess.getRightSideAccess().getGroup_3(), "rule__RightSide__Group_3__0");
					put(grammarAccess.getRightSideAccess().getGroup_4(), "rule__RightSide__Group_4__0");
					put(grammarAccess.getRightSideAccess().getGroup_5(), "rule__RightSide__Group_5__0");
					put(grammarAccess.getRightSideAccess().getGroup_6(), "rule__RightSide__Group_6__0");
					put(grammarAccess.getSynchronizedAccess().getGroup(), "rule__Synchronized__Group__0");
					put(grammarAccess.getUndefAccess().getGroup(), "rule__Undef__Group__0");
					put(grammarAccess.getOutputOperationAccess().getGroup(), "rule__OutputOperation__Group__0");
					put(grammarAccess.getOutputOperationAccess().getGroup_4(), "rule__OutputOperation__Group_4__0");
					put(grammarAccess.getOutputOperationAccess().getGroup_4_3(), "rule__OutputOperation__Group_4_3__0");
					put(grammarAccess.getInstallFuncitonAccess().getGroup(), "rule__InstallFunciton__Group__0");
					put(grammarAccess.getInstallFuncitonAccess().getGroup_3(), "rule__InstallFunciton__Group_3__0");
					put(grammarAccess.getInputOperationAccess().getGroup(), "rule__InputOperation__Group__0");
					put(grammarAccess.getInputOperationAccess().getGroup_1(), "rule__InputOperation__Group_1__0");
					put(grammarAccess.getPreIncrementDecrementAccess().getGroup(), "rule__PreIncrementDecrement__Group__0");
					put(grammarAccess.getForAccess().getGroup(), "rule__For__Group__0");
					put(grammarAccess.getBodyAccess().getGroup(), "rule__Body__Group__0");
					put(grammarAccess.getConditionAccess().getGroup_0(), "rule__Condition__Group_0__0");
					put(grammarAccess.getConditionAccess().getGroup_1(), "rule__Condition__Group_1__0");
					put(grammarAccess.getRightConditionAccess().getGroup(), "rule__RightCondition__Group__0");
					put(grammarAccess.getForeachAccess().getGroup(), "rule__Foreach__Group__0");
					put(grammarAccess.getExpressionAccess().getGroup(), "rule__Expression__Group__0");
					put(grammarAccess.getExpressionAccess().getGroup_1(), "rule__Expression__Group_1__0");
					put(grammarAccess.getTerminalExpressionAccess().getGroup_0(), "rule__TerminalExpression__Group_0__0");
					put(grammarAccess.getTerminalExpressionAccess().getGroup_1(), "rule__TerminalExpression__Group_1__0");
					put(grammarAccess.getTerminalExpressionAccess().getGroup_2(), "rule__TerminalExpression__Group_2__0");
					put(grammarAccess.getTerminalExpressionAccess().getGroup_3(), "rule__TerminalExpression__Group_3__0");
					put(grammarAccess.getTerminalExpressionAccess().getGroup_4(), "rule__TerminalExpression__Group_4__0");
					put(grammarAccess.getTerminalExpressionAccess().getGroup_5(), "rule__TerminalExpression__Group_5__0");
					put(grammarAccess.getVariablePathAccess().getGroup_0(), "rule__VariablePath__Group_0__0");
					put(grammarAccess.getVariablePathAccess().getGroup_0_3(), "rule__VariablePath__Group_0_3__0");
					put(grammarAccess.getVariablePathAccess().getGroup_0_4_0(), "rule__VariablePath__Group_0_4_0__0");
					put(grammarAccess.getVariablePathAccess().getGroup_0_4_0_2(), "rule__VariablePath__Group_0_4_0_2__0");
					put(grammarAccess.getVariablePathAccess().getGroup_0_4_1(), "rule__VariablePath__Group_0_4_1__0");
					put(grammarAccess.getVariablePathAccess().getGroup_1(), "rule__VariablePath__Group_1__0");
					put(grammarAccess.getVariablePathAccess().getGroup_1_2_0(), "rule__VariablePath__Group_1_2_0__0");
					put(grammarAccess.getVariablePathAccess().getGroup_1_2_0_2(), "rule__VariablePath__Group_1_2_0_2__0");
					put(grammarAccess.getVariablePathAccess().getGroup_1_2_1(), "rule__VariablePath__Group_1_2_1__0");
					put(grammarAccess.getWithAccess().getGroup(), "rule__With__Group__0");
					put(grammarAccess.getNDChoiceStatementAccess().getGroup(), "rule__NDChoiceStatement__Group__0");
					put(grammarAccess.getNDChoiceStatementAccess().getGroup_1(), "rule__NDChoiceStatement__Group_1__0");
					put(grammarAccess.getNDChoiceStatementAccess().getGroup_1_1_0(), "rule__NDChoiceStatement__Group_1_1_0__0");
					put(grammarAccess.getNDChoiceStatementAccess().getGroup_1_1_1(), "rule__NDChoiceStatement__Group_1_1_1__0");
					put(grammarAccess.getInterfaceAccess().getGroup(), "rule__Interface__Group__0");
					put(grammarAccess.getInputPortStatementAccess().getGroup(), "rule__InputPortStatement__Group__0");
					put(grammarAccess.getOutputPortStatementAccess().getGroup(), "rule__OutputPortStatement__Group__0");
					put(grammarAccess.getOneWayOperationAccess().getGroup(), "rule__OneWayOperation__Group__0");
					put(grammarAccess.getOneWayOperationAccess().getGroup_4(), "rule__OneWayOperation__Group_4__0");
					put(grammarAccess.getOneWayOperationAccess().getGroup_5(), "rule__OneWayOperation__Group_5__0");
					put(grammarAccess.getOneWayOperationAccess().getGroup_5_2(), "rule__OneWayOperation__Group_5_2__0");
					put(grammarAccess.getRequestResponseOperationAccess().getGroup(), "rule__RequestResponseOperation__Group__0");
					put(grammarAccess.getRequestResponseOperationAccess().getGroup_4(), "rule__RequestResponseOperation__Group_4__0");
					put(grammarAccess.getRequestResponseOperationAccess().getGroup_4_0(), "rule__RequestResponseOperation__Group_4_0__0");
					put(grammarAccess.getRequestResponseOperationAccess().getGroup_4_1(), "rule__RequestResponseOperation__Group_4_1__0");
					put(grammarAccess.getRequestResponseOperationAccess().getGroup_5(), "rule__RequestResponseOperation__Group_5__0");
					put(grammarAccess.getRequestResponseOperationAccess().getGroup_5_2(), "rule__RequestResponseOperation__Group_5_2__0");
					put(grammarAccess.getRequestResponseOperationAccess().getGroup_6(), "rule__RequestResponseOperation__Group_6__0");
					put(grammarAccess.getRequestResponseOperationAccess().getGroup_6_2(), "rule__RequestResponseOperation__Group_6_2__0");
					put(grammarAccess.getRequestResponseOperationAccess().getGroup_6_2_0(), "rule__RequestResponseOperation__Group_6_2_0__0");
					put(grammarAccess.getRequestResponseOperationAccess().getGroup_6_2_1(), "rule__RequestResponseOperation__Group_6_2_1__0");
					put(grammarAccess.getRequestResponseOperationAccess().getGroup_6_3(), "rule__RequestResponseOperation__Group_6_3__0");
					put(grammarAccess.getRequestResponseOperationAccess().getGroup_6_3_2(), "rule__RequestResponseOperation__Group_6_3_2__0");
					put(grammarAccess.getTypeDefinitionAccess().getGroup_1(), "rule__TypeDefinition__Group_1__0");
					put(grammarAccess.getLocationAccess().getGroup(), "rule__Location__Group__0");
					put(grammarAccess.getUriAccess().getGroup_0(), "rule__Uri__Group_0__0");
					put(grammarAccess.getUriAccess().getGroup_1(), "rule__Uri__Group_1__0");
					put(grammarAccess.getInterfacesAccess().getGroup(), "rule__Interfaces__Group__0");
					put(grammarAccess.getInterfacesAccess().getGroup_3(), "rule__Interfaces__Group_3__0");
					put(grammarAccess.getProtocolAccess().getGroup(), "rule__Protocol__Group__0");
					put(grammarAccess.getProtocolConfigurationAccess().getGroup(), "rule__ProtocolConfiguration__Group__0");
					put(grammarAccess.getRedirectsAccess().getGroup(), "rule__Redirects__Group__0");
					put(grammarAccess.getRedirectsAccess().getGroup_5(), "rule__Redirects__Group_5__0");
					put(grammarAccess.getAggregatesAccess().getGroup(), "rule__Aggregates__Group__0");
					put(grammarAccess.getAggregatesAccess().getGroup_3(), "rule__Aggregates__Group_3__0");
					put(grammarAccess.getProgramAccess().getIncludeAssignment_0_0(), "rule__Program__IncludeAssignment_0_0");
					put(grammarAccess.getProgramAccess().getPortsAssignment_0_1(), "rule__Program__PortsAssignment_0_1");
					put(grammarAccess.getProgramAccess().getInterfaceAssignment_0_2(), "rule__Program__InterfaceAssignment_0_2");
					put(grammarAccess.getProgramAccess().getTypesAssignment_0_3(), "rule__Program__TypesAssignment_0_3");
					put(grammarAccess.getProgramAccess().getInitAssignment_0_4(), "rule__Program__InitAssignment_0_4");
					put(grammarAccess.getProgramAccess().getExecutionAssignment_0_5(), "rule__Program__ExecutionAssignment_0_5");
					put(grammarAccess.getProgramAccess().getDefineAssignment_0_6(), "rule__Program__DefineAssignment_0_6");
					put(grammarAccess.getProgramAccess().getMainAssignment_1(), "rule__Program__MainAssignment_1");
					put(grammarAccess.getIncludeAccess().getPathAssignment_1(), "rule__Include__PathAssignment_1");
					put(grammarAccess.getTypeAccess().getNameAssignment_1(), "rule__Type__NameAssignment_1");
					put(grammarAccess.getTypeAccess().getTypedefAssignment_4(), "rule__Type__TypedefAssignment_4");
					put(grammarAccess.getTypedefAccess().getSubtypesAssignment_2(), "rule__Typedef__SubtypesAssignment_2");
					put(grammarAccess.getSubtypesAccess().getNameAssignment_0_1_1(), "rule__Subtypes__NameAssignment_0_1_1");
					put(grammarAccess.getSubtypesAccess().getNative_type_subAssignment_0_1_4(), "rule__Subtypes__Native_type_subAssignment_0_1_4");
					put(grammarAccess.getSubtypesAccess().getTypedefAssignment_0_1_5(), "rule__Subtypes__TypedefAssignment_0_1_5");
					put(grammarAccess.getNative_type_subAccess().getTypeAssignment_1_4(), "rule__Native_type_sub__TypeAssignment_1_4");
					put(grammarAccess.getDefineAccess().getNameAssignment_1(), "rule__Define__NameAssignment_1");
					put(grammarAccess.getDefineAccess().getMainrocessAssignment_2(), "rule__Define__MainrocessAssignment_2");
					put(grammarAccess.getInitAccess().getNameAssignment_0(), "rule__Init__NameAssignment_0");
					put(grammarAccess.getInitAccess().getMainrocessAssignment_1(), "rule__Init__MainrocessAssignment_1");
					put(grammarAccess.getMainAccess().getNameAssignment_0(), "rule__Main__NameAssignment_0");
					put(grammarAccess.getMainAccess().getMainrocessAssignment_1(), "rule__Main__MainrocessAssignment_1");
					put(grammarAccess.getMainProcessAccess().getParallelStatementAssignment_2(), "rule__MainProcess__ParallelStatementAssignment_2");
					put(grammarAccess.getProcessAccess().getChildrenAssignment_0_2(), "rule__Process__ChildrenAssignment_0_2");
					put(grammarAccess.getProcessAccess().getChildrenAssignment_1_1(), "rule__Process__ChildrenAssignment_1_1");
					put(grammarAccess.getParallelStatementAccess().getChildrenAssignment_1_0(), "rule__ParallelStatement__ChildrenAssignment_1_0");
					put(grammarAccess.getParallelStatementAccess().getChildrenAssignment_1_1_1(), "rule__ParallelStatement__ChildrenAssignment_1_1_1");
					put(grammarAccess.getSequenceStatementAccess().getChildrenAssignment_1_0(), "rule__SequenceStatement__ChildrenAssignment_1_0");
					put(grammarAccess.getSequenceStatementAccess().getChildrenAssignment_1_1_1(), "rule__SequenceStatement__ChildrenAssignment_1_1_1");
					put(grammarAccess.getBasicStatementAccess().getProcessAssignment_0(), "rule__BasicStatement__ProcessAssignment_0");
					put(grammarAccess.getBasicStatementAccess().getAssignStatementOrPostIncrementDecrementAssignment_1(), "rule__BasicStatement__AssignStatementOrPostIncrementDecrementAssignment_1");
					put(grammarAccess.getBasicStatementAccess().getNDChoiceStatementAssignment_2(), "rule__BasicStatement__NDChoiceStatementAssignment_2");
					put(grammarAccess.getBasicStatementAccess().getPreIncrementDecrementAssignment_3(), "rule__BasicStatement__PreIncrementDecrementAssignment_3");
					put(grammarAccess.getBasicStatementAccess().getCallAssignment_11(), "rule__BasicStatement__CallAssignment_11");
					put(grammarAccess.getLinkInAccess().getNameAssignment_3(), "rule__LinkIn__NameAssignment_3");
					put(grammarAccess.getAssignStatementOrPostIncrementDecrementOrInputOperationAccess().getVariablePathAssignment_1(), "rule__AssignStatementOrPostIncrementDecrementOrInputOperation__VariablePathAssignment_1");
					put(grammarAccess.getAssignStatementOrPostIncrementDecrementOrInputOperationAccess().getRightSideAssignment_2(), "rule__AssignStatementOrPostIncrementDecrementOrInputOperation__RightSideAssignment_2");
					put(grammarAccess.getRightSideAccess().getExpressionAssignment_0_2(), "rule__RightSide__ExpressionAssignment_0_2");
					put(grammarAccess.getRightSideAccess().getVariablePathAssignment_3_2(), "rule__RightSide__VariablePathAssignment_3_2");
					put(grammarAccess.getRightSideAccess().getVariablePathAssignment_4_2(), "rule__RightSide__VariablePathAssignment_4_2");
					put(grammarAccess.getRightSideAccess().getVariablePathAssignment_5_1(), "rule__RightSide__VariablePathAssignment_5_1");
					put(grammarAccess.getRightSideAccess().getInputOperationAssignment_5_3(), "rule__RightSide__InputOperationAssignment_5_3");
					put(grammarAccess.getRightSideAccess().getOutputOperationAssignment_6_1(), "rule__RightSide__OutputOperationAssignment_6_1");
					put(grammarAccess.getSynchronizedAccess().getNameAssignment_2(), "rule__Synchronized__NameAssignment_2");
					put(grammarAccess.getSynchronizedAccess().getMainProcessAssignment_4(), "rule__Synchronized__MainProcessAssignment_4");
					put(grammarAccess.getUndefAccess().getVariablePathAssignment_2(), "rule__Undef__VariablePathAssignment_2");
					put(grammarAccess.getOutputOperationAccess().getNameAssignment_0(), "rule__OutputOperation__NameAssignment_0");
					put(grammarAccess.getOutputOperationAccess().getExpressionAssignment_2(), "rule__OutputOperation__ExpressionAssignment_2");
					put(grammarAccess.getOutputOperationAccess().getVariablePathAssignment_4_1(), "rule__OutputOperation__VariablePathAssignment_4_1");
					put(grammarAccess.getOutputOperationAccess().getInstallFunctionAssignment_4_3_1(), "rule__OutputOperation__InstallFunctionAssignment_4_3_1");
					put(grammarAccess.getInstallFuncitonAccess().getNameAssignment_0_0(), "rule__InstallFunciton__NameAssignment_0_0");
					put(grammarAccess.getInstallFuncitonAccess().getProcessAssignment_2(), "rule__InstallFunciton__ProcessAssignment_2");
					put(grammarAccess.getInstallFuncitonAccess().getNameAssignment_3_1_0(), "rule__InstallFunciton__NameAssignment_3_1_0");
					put(grammarAccess.getInstallFuncitonAccess().getParallelStatementAssignment_3_3(), "rule__InstallFunciton__ParallelStatementAssignment_3_3");
					put(grammarAccess.getInputOperationAccess().getExpressionAssignment_1_1(), "rule__InputOperation__ExpressionAssignment_1_1");
					put(grammarAccess.getInputOperationAccess().getMainProcessAssignment_1_3(), "rule__InputOperation__MainProcessAssignment_1_3");
					put(grammarAccess.getPreIncrementDecrementAccess().getVariablePathAssignment_1(), "rule__PreIncrementDecrement__VariablePathAssignment_1");
					put(grammarAccess.getForAccess().getParallelStatementAssignment_2(), "rule__For__ParallelStatementAssignment_2");
					put(grammarAccess.getForAccess().getConditionAssignment_4(), "rule__For__ConditionAssignment_4");
					put(grammarAccess.getForAccess().getParallelStatementAssignment_6(), "rule__For__ParallelStatementAssignment_6");
					put(grammarAccess.getForAccess().getBodyAssignment_7(), "rule__For__BodyAssignment_7");
					put(grammarAccess.getConditionAccess().getExpressionAssignment_0_1(), "rule__Condition__ExpressionAssignment_0_1");
					put(grammarAccess.getConditionAccess().getVariablePathAssignment_1_0_0(), "rule__Condition__VariablePathAssignment_1_0_0");
					put(grammarAccess.getConditionAccess().getRightConditionAssignment_1_1(), "rule__Condition__RightConditionAssignment_1_1");
					put(grammarAccess.getRightConditionAccess().getExpressionAssignment_1(), "rule__RightCondition__ExpressionAssignment_1");
					put(grammarAccess.getForeachAccess().getVar1Assignment_3(), "rule__Foreach__Var1Assignment_3");
					put(grammarAccess.getForeachAccess().getVar2Assignment_5(), "rule__Foreach__Var2Assignment_5");
					put(grammarAccess.getForeachAccess().getBodyAssignment_6(), "rule__Foreach__BodyAssignment_6");
					put(grammarAccess.getExpressionAccess().getOpAssignment_1_1(), "rule__Expression__OpAssignment_1_1");
					put(grammarAccess.getExpressionAccess().getRightAssignment_1_2(), "rule__Expression__RightAssignment_1_2");
					put(grammarAccess.getTerminalExpressionAccess().getValueAssignment_1_2(), "rule__TerminalExpression__ValueAssignment_1_2");
					put(grammarAccess.getTerminalExpressionAccess().getValueAssignment_2_2(), "rule__TerminalExpression__ValueAssignment_2_2");
					put(grammarAccess.getTerminalExpressionAccess().getValueAssignment_3_1(), "rule__TerminalExpression__ValueAssignment_3_1");
					put(grammarAccess.getTerminalExpressionAccess().getVariablePathAssignment_4_1(), "rule__TerminalExpression__VariablePathAssignment_4_1");
					put(grammarAccess.getTerminalExpressionAccess().getVariablePathAssignment_5_0(), "rule__TerminalExpression__VariablePathAssignment_5_0");
					put(grammarAccess.getVariablePathAccess().getDotAssignment_0_1(), "rule__VariablePath__DotAssignment_0_1");
					put(grammarAccess.getVariablePathAccess().getNameAssignment_0_2(), "rule__VariablePath__NameAssignment_0_2");
					put(grammarAccess.getVariablePathAccess().getChildrenAssignment_0_3_1(), "rule__VariablePath__ChildrenAssignment_0_3_1");
					put(grammarAccess.getVariablePathAccess().getChildrenAssignment_0_4_0_2_1(), "rule__VariablePath__ChildrenAssignment_0_4_0_2_1");
					put(grammarAccess.getVariablePathAccess().getChildrenAssignment_0_4_1_2(), "rule__VariablePath__ChildrenAssignment_0_4_1_2");
					put(grammarAccess.getVariablePathAccess().getChildrenAssignment_1_2_0_2_1(), "rule__VariablePath__ChildrenAssignment_1_2_0_2_1");
					put(grammarAccess.getVariablePathAccess().getChildrenAssignment_1_2_1_2(), "rule__VariablePath__ChildrenAssignment_1_2_1_2");
					put(grammarAccess.getWithAccess().getNameAssignment_3(), "rule__With__NameAssignment_3");
					put(grammarAccess.getWithAccess().getMainrocessAssignment_5(), "rule__With__MainrocessAssignment_5");
					put(grammarAccess.getNDChoiceStatementAccess().getVariablePathAssignment_1_1_1_0(), "rule__NDChoiceStatement__VariablePathAssignment_1_1_1_0");
					put(grammarAccess.getNDChoiceStatementAccess().getVariablePathAssignment_1_1_1_2(), "rule__NDChoiceStatement__VariablePathAssignment_1_1_1_2");
					put(grammarAccess.getNDChoiceStatementAccess().getInputOperationAssignment_1_1_1_4(), "rule__NDChoiceStatement__InputOperationAssignment_1_1_1_4");
					put(grammarAccess.getNDChoiceStatementAccess().getMainProcessAssignment_1_3(), "rule__NDChoiceStatement__MainProcessAssignment_1_3");
					put(grammarAccess.getInterfaceAccess().getNameAssignment_1(), "rule__Interface__NameAssignment_1");
					put(grammarAccess.getInterfaceAccess().getRequestResponseOperationAssignment_3_0(), "rule__Interface__RequestResponseOperationAssignment_3_0");
					put(grammarAccess.getInterfaceAccess().getOneWayOperationAssignment_3_1(), "rule__Interface__OneWayOperationAssignment_3_1");
					put(grammarAccess.getPortAccess().getInputPortStatementAssignment_0(), "rule__Port__InputPortStatementAssignment_0");
					put(grammarAccess.getPortAccess().getOutputPortStatementAssignment_1(), "rule__Port__OutputPortStatementAssignment_1");
					put(grammarAccess.getInputPortStatementAccess().getNameAssignment_1(), "rule__InputPortStatement__NameAssignment_1");
					put(grammarAccess.getInputPortStatementAccess().getLocationAssignment_3_0(), "rule__InputPortStatement__LocationAssignment_3_0");
					put(grammarAccess.getInputPortStatementAccess().getProtocolAssignment_3_1(), "rule__InputPortStatement__ProtocolAssignment_3_1");
					put(grammarAccess.getInputPortStatementAccess().getOneWayOperationAssignment_3_2(), "rule__InputPortStatement__OneWayOperationAssignment_3_2");
					put(grammarAccess.getInputPortStatementAccess().getRequestResponseOperationAssignment_3_3(), "rule__InputPortStatement__RequestResponseOperationAssignment_3_3");
					put(grammarAccess.getInputPortStatementAccess().getRedirectsAssignment_3_4(), "rule__InputPortStatement__RedirectsAssignment_3_4");
					put(grammarAccess.getInputPortStatementAccess().getAggregatesAssignment_3_5(), "rule__InputPortStatement__AggregatesAssignment_3_5");
					put(grammarAccess.getInputPortStatementAccess().getIntefacesAssignment_3_6(), "rule__InputPortStatement__IntefacesAssignment_3_6");
					put(grammarAccess.getOutputPortStatementAccess().getNameAssignment_1(), "rule__OutputPortStatement__NameAssignment_1");
					put(grammarAccess.getOutputPortStatementAccess().getLocationAssignment_3_0(), "rule__OutputPortStatement__LocationAssignment_3_0");
					put(grammarAccess.getOutputPortStatementAccess().getProtocolAssignment_3_1(), "rule__OutputPortStatement__ProtocolAssignment_3_1");
					put(grammarAccess.getOutputPortStatementAccess().getOneWayOperationAssignment_3_2(), "rule__OutputPortStatement__OneWayOperationAssignment_3_2");
					put(grammarAccess.getOutputPortStatementAccess().getRequestResponseOperationAssignment_3_3(), "rule__OutputPortStatement__RequestResponseOperationAssignment_3_3");
					put(grammarAccess.getOutputPortStatementAccess().getIntefacesAssignment_3_4(), "rule__OutputPortStatement__IntefacesAssignment_3_4");
					put(grammarAccess.getOneWayOperationAccess().getNameAssignment_3(), "rule__OneWayOperation__NameAssignment_3");
					put(grammarAccess.getOneWayOperationAccess().getTypeDefinitionAssignment_4_1(), "rule__OneWayOperation__TypeDefinitionAssignment_4_1");
					put(grammarAccess.getOneWayOperationAccess().getChildrenAssignment_5_1(), "rule__OneWayOperation__ChildrenAssignment_5_1");
					put(grammarAccess.getOneWayOperationAccess().getTypeDefinitionAssignment_5_2_1(), "rule__OneWayOperation__TypeDefinitionAssignment_5_2_1");
					put(grammarAccess.getRequestResponseOperationAccess().getNameAssignment_3(), "rule__RequestResponseOperation__NameAssignment_3");
					put(grammarAccess.getRequestResponseOperationAccess().getTypeDefinitionAssignment_4_0_1(), "rule__RequestResponseOperation__TypeDefinitionAssignment_4_0_1");
					put(grammarAccess.getRequestResponseOperationAccess().getTypeDefinitionAssignment_4_1_1(), "rule__RequestResponseOperation__TypeDefinitionAssignment_4_1_1");
					put(grammarAccess.getRequestResponseOperationAccess().getNameAssignment_5_1(), "rule__RequestResponseOperation__NameAssignment_5_1");
					put(grammarAccess.getRequestResponseOperationAccess().getTypeDefinitionAssignment_5_2_1(), "rule__RequestResponseOperation__TypeDefinitionAssignment_5_2_1");
					put(grammarAccess.getRequestResponseOperationAccess().getNameAssignment_6_1(), "rule__RequestResponseOperation__NameAssignment_6_1");
					put(grammarAccess.getRequestResponseOperationAccess().getTypeDefinitionAssignment_6_2_0_1(), "rule__RequestResponseOperation__TypeDefinitionAssignment_6_2_0_1");
					put(grammarAccess.getRequestResponseOperationAccess().getTypeDefinitionAssignment_6_2_1_1(), "rule__RequestResponseOperation__TypeDefinitionAssignment_6_2_1_1");
					put(grammarAccess.getRequestResponseOperationAccess().getNameAssignment_6_3_1(), "rule__RequestResponseOperation__NameAssignment_6_3_1");
					put(grammarAccess.getRequestResponseOperationAccess().getTypeDefinitionAssignment_6_3_2_1(), "rule__RequestResponseOperation__TypeDefinitionAssignment_6_3_2_1");
					put(grammarAccess.getTypeDefinitionAccess().getTypeAssignment_0(), "rule__TypeDefinition__TypeAssignment_0");
					put(grammarAccess.getLocationAccess().getUriAssignment_2(), "rule__Location__UriAssignment_2");
					put(grammarAccess.getUriAccess().getNameAssignment_0_1(), "rule__Uri__NameAssignment_0_1");
					put(grammarAccess.getInterfacesAccess().getNameAssignment_2(), "rule__Interfaces__NameAssignment_2");
					put(grammarAccess.getInterfacesAccess().getNameAssignment_3_1(), "rule__Interfaces__NameAssignment_3_1");
					put(grammarAccess.getProtocolAccess().getNameAssignment_2(), "rule__Protocol__NameAssignment_2");
					put(grammarAccess.getRedirectsAccess().getNameAssignment_2(), "rule__Redirects__NameAssignment_2");
					put(grammarAccess.getRedirectsAccess().getOutputPortIdentifierAssignment_4(), "rule__Redirects__OutputPortIdentifierAssignment_4");
					put(grammarAccess.getRedirectsAccess().getNameAssignment_5_1(), "rule__Redirects__NameAssignment_5_1");
					put(grammarAccess.getRedirectsAccess().getOutputPortIdentifierAssignment_5_3(), "rule__Redirects__OutputPortIdentifierAssignment_5_3");
					put(grammarAccess.getAggregatesAccess().getNameAssignment_2(), "rule__Aggregates__NameAssignment_2");
					put(grammarAccess.getAggregatesAccess().getNameAssignment_3_1(), "rule__Aggregates__NameAssignment_3_1");
					put(grammarAccess.getInterfaceAccess().getUnorderedGroup_3(), "rule__Interface__UnorderedGroup_3");
					put(grammarAccess.getInputPortStatementAccess().getUnorderedGroup_3(), "rule__InputPortStatement__UnorderedGroup_3");
					put(grammarAccess.getOutputPortStatementAccess().getUnorderedGroup_3(), "rule__OutputPortStatement__UnorderedGroup_3");
				}
			};
		}
		return nameMappings.get(element);
	}
	
	@Override
	protected Collection<FollowElement> getFollowElements(AbstractInternalContentAssistParser parser) {
		try {
			jolie.xtext.ui.contentassist.antlr.internal.InternalJolieParser typedParser = (jolie.xtext.ui.contentassist.antlr.internal.InternalJolieParser) parser;
			typedParser.entryRuleProgram();
			return typedParser.getFollowElements();
		} catch(RecognitionException ex) {
			throw new RuntimeException(ex);
		}		
	}
	
	@Override
	protected String[] getInitialHiddenTokens() {
		return new String[] { "RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT" };
	}
	
	public JolieGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(JolieGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
