/*
* generated by Xtext
*/
package jolie.xtext.ui.contentassist.antlr;

import java.util.Collection;
import java.util.Map;
import java.util.HashMap;

import org.antlr.runtime.RecognitionException;
import org.eclipse.xtext.AbstractElement;
import org.eclipse.xtext.ui.editor.contentassist.antlr.AbstractContentAssistParser;
import org.eclipse.xtext.ui.editor.contentassist.antlr.FollowElement;
import org.eclipse.xtext.ui.editor.contentassist.antlr.internal.AbstractInternalContentAssistParser;

import com.google.inject.Inject;

import jolie.xtext.services.JolieGrammarAccess;

public class JolieParser extends AbstractContentAssistParser {
	
	@Inject
	private JolieGrammarAccess grammarAccess;
	
	private Map<AbstractElement, String> nameMappings;
	
	@Override
	protected jolie.xtext.ui.contentassist.antlr.internal.InternalJolieParser createParser() {
		jolie.xtext.ui.contentassist.antlr.internal.InternalJolieParser result = new jolie.xtext.ui.contentassist.antlr.internal.InternalJolieParser(null);
		result.setGrammarAccess(grammarAccess);
		return result;
	}
	
	@Override
	protected String getRuleName(AbstractElement element) {
		if (nameMappings == null) {
			nameMappings = new HashMap<AbstractElement, String>() {
				private static final long serialVersionUID = 1L;
				{
					put(grammarAccess.getProcessAccess().getAlternatives(), "rule__Process__Alternatives");
					put(grammarAccess.getBasicStatementAccess().getAlternatives(), "rule__BasicStatement__Alternatives");
					put(grammarAccess.getExpressionAccess().getOpAlternatives_1_1_0(), "rule__Expression__OpAlternatives_1_1_0");
					put(grammarAccess.getTerminalExpressionAccess().getAlternatives(), "rule__TerminalExpression__Alternatives");
					put(grammarAccess.getProgramAccess().getGroup(), "rule__Program__Group__0");
					put(grammarAccess.getMainProcessAccess().getGroup(), "rule__MainProcess__Group__0");
					put(grammarAccess.getProcessAccess().getGroup_0(), "rule__Process__Group_0__0");
					put(grammarAccess.getProcessAccess().getGroup_1(), "rule__Process__Group_1__0");
					put(grammarAccess.getParallelStatementAccess().getGroup(), "rule__ParallelStatement__Group__0");
					put(grammarAccess.getParallelStatementAccess().getGroup_1(), "rule__ParallelStatement__Group_1__0");
					put(grammarAccess.getParallelStatementAccess().getGroup_1_1(), "rule__ParallelStatement__Group_1_1__0");
					put(grammarAccess.getSequenceStatementAccess().getGroup(), "rule__SequenceStatement__Group__0");
					put(grammarAccess.getSequenceStatementAccess().getGroup_1(), "rule__SequenceStatement__Group_1__0");
					put(grammarAccess.getSequenceStatementAccess().getGroup_1_1(), "rule__SequenceStatement__Group_1_1__0");
					put(grammarAccess.getBasicStatementAccess().getGroup_0(), "rule__BasicStatement__Group_0__0");
					put(grammarAccess.getBasicStatementAccess().getGroup_1(), "rule__BasicStatement__Group_1__0");
					put(grammarAccess.getBasicStatementAccess().getGroup_2(), "rule__BasicStatement__Group_2__0");
					put(grammarAccess.getBasicStatementAccess().getGroup_3(), "rule__BasicStatement__Group_3__0");
					put(grammarAccess.getAssignStatementAccess().getGroup(), "rule__AssignStatement__Group__0");
					put(grammarAccess.getPostIncrementStatementAccess().getGroup(), "rule__PostIncrementStatement__Group__0");
					put(grammarAccess.getPostDecrementStatementAccess().getGroup(), "rule__PostDecrementStatement__Group__0");
					put(grammarAccess.getExpressionAccess().getGroup(), "rule__Expression__Group__0");
					put(grammarAccess.getExpressionAccess().getGroup_1(), "rule__Expression__Group_1__0");
					put(grammarAccess.getTerminalExpressionAccess().getGroup_0(), "rule__TerminalExpression__Group_0__0");
					put(grammarAccess.getTerminalExpressionAccess().getGroup_1(), "rule__TerminalExpression__Group_1__0");
					put(grammarAccess.getTerminalExpressionAccess().getGroup_2(), "rule__TerminalExpression__Group_2__0");
					put(grammarAccess.getTerminalExpressionAccess().getGroup_3(), "rule__TerminalExpression__Group_3__0");
					put(grammarAccess.getProgramAccess().getMainAssignment_1(), "rule__Program__MainAssignment_1");
					put(grammarAccess.getMainAccess().getMainrocessAssignment(), "rule__Main__MainrocessAssignment");
					put(grammarAccess.getMainProcessAccess().getParallelStatementAssignment_2(), "rule__MainProcess__ParallelStatementAssignment_2");
					put(grammarAccess.getProcessAccess().getChildrenAssignment_0_2(), "rule__Process__ChildrenAssignment_0_2");
					put(grammarAccess.getProcessAccess().getChildrenAssignment_1_1(), "rule__Process__ChildrenAssignment_1_1");
					put(grammarAccess.getParallelStatementAccess().getChildrenAssignment_1_0(), "rule__ParallelStatement__ChildrenAssignment_1_0");
					put(grammarAccess.getParallelStatementAccess().getChildrenAssignment_1_1_1(), "rule__ParallelStatement__ChildrenAssignment_1_1_1");
					put(grammarAccess.getSequenceStatementAccess().getChildrenAssignment_1_0(), "rule__SequenceStatement__ChildrenAssignment_1_0");
					put(grammarAccess.getSequenceStatementAccess().getChildrenAssignment_1_1_1(), "rule__SequenceStatement__ChildrenAssignment_1_1_1");
					put(grammarAccess.getBasicStatementAccess().getProcessAssignment_0_1(), "rule__BasicStatement__ProcessAssignment_0_1");
					put(grammarAccess.getBasicStatementAccess().getAssignStatementAssignment_1_1(), "rule__BasicStatement__AssignStatementAssignment_1_1");
					put(grammarAccess.getBasicStatementAccess().getPostIncrementStatementAssignment_2_1(), "rule__BasicStatement__PostIncrementStatementAssignment_2_1");
					put(grammarAccess.getBasicStatementAccess().getPostDecrementStatementAssignment_3_1(), "rule__BasicStatement__PostDecrementStatementAssignment_3_1");
					put(grammarAccess.getAssignStatementAccess().getNameAssignment_1(), "rule__AssignStatement__NameAssignment_1");
					put(grammarAccess.getAssignStatementAccess().getExpressionAssignment_4(), "rule__AssignStatement__ExpressionAssignment_4");
					put(grammarAccess.getPostIncrementStatementAccess().getNameAssignment_1(), "rule__PostIncrementStatement__NameAssignment_1");
					put(grammarAccess.getPostDecrementStatementAccess().getNaemAssignment_1(), "rule__PostDecrementStatement__NaemAssignment_1");
					put(grammarAccess.getExpressionAccess().getOpAssignment_1_1(), "rule__Expression__OpAssignment_1_1");
					put(grammarAccess.getExpressionAccess().getRightAssignment_1_2(), "rule__Expression__RightAssignment_1_2");
					put(grammarAccess.getTerminalExpressionAccess().getValueAssignment_1_1(), "rule__TerminalExpression__ValueAssignment_1_1");
					put(grammarAccess.getTerminalExpressionAccess().getValueAssignment_2_1(), "rule__TerminalExpression__ValueAssignment_2_1");
					put(grammarAccess.getTerminalExpressionAccess().getValueAssignment_3_1(), "rule__TerminalExpression__ValueAssignment_3_1");
				}
			};
		}
		return nameMappings.get(element);
	}
	
	@Override
	protected Collection<FollowElement> getFollowElements(AbstractInternalContentAssistParser parser) {
		try {
			jolie.xtext.ui.contentassist.antlr.internal.InternalJolieParser typedParser = (jolie.xtext.ui.contentassist.antlr.internal.InternalJolieParser) parser;
			typedParser.entryRuleProgram();
			return typedParser.getFollowElements();
		} catch(RecognitionException ex) {
			throw new RuntimeException(ex);
		}		
	}
	
	@Override
	protected String[] getInitialHiddenTokens() {
		return new String[] { "RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT" };
	}
	
	public JolieGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(JolieGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
